# secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_USERNAME: YWRtaW4=        # "admin"
  DB_PASSWORD: c2VjcmV0MTIz    # "secret123"
  API_KEY: YXBpLWtleS12YWx1ZQ== # "api-key-value"



# Use Secrets as Environment Variables (Recommended for credentials)
# pod-env.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod-env
spec:
  containers:
    - name: app
      image: nginx
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_USERNAME

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD

        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: API_KEY


# Inside container:
# $DB_USERNAME = admin
# $DB_PASSWORD = secret123
# $API_KEY     = api-key-value


# ----------------------------------

# Use All Secret Keys at Once (envFrom)
# pod-envfrom.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod-envfrom
spec:
  containers:
    - name: app
      image: nginx
      envFrom:
        - secretRef:
            name: app-secret


# Inside container:
# $DB_USERNAME=admin
# $DB_PASSWORD=secret123
# $API_KEY=api-key-value


# ----------------------------------

# Mount Secret as Files (Best for TLS, SSH keys, config files)
# pod-volume.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod-volume
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/app-secret"   # directory where files appear
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret

# Inside container:
# /etc/app-secret/DB_USERNAME
# /etc/app-secret/DB_PASSWORD
# /etc/app-secret/API_KEY
